name: tryone
favicon: null
layout_spectrum: 0.24124
typography_spectrum: 0.25793
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f2c36'
    - '#5c8963'
    - '#dd406a'
    - '#db0049'
    - '#ef778a'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
